// Code generated by the Encore 1.50.6 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the  Encore application.
 */
export class Client {
    public readonly ai_analysis: ai_analysis.ServiceClient
    public readonly ai_history: ai_history.ServiceClient
    public readonly ai_text_detector: ai_text_detector.ServiceClient
    public readonly au_tax: au_tax.ServiceClient
    public readonly auth: auth.ServiceClient
    public readonly blog: blog.ServiceClient
    public readonly blogV2: blogV2.ServiceClient
    public readonly calc_history: calc_history.ServiceClient
    public readonly caption_gen: caption_gen.ServiceClient
    public readonly compatibility: compatibility.ServiceClient
    public readonly exchange: exchange.ServiceClient
    public readonly health: health.ServiceClient
    public readonly pageviews: pageviews.ServiceClient
    public readonly pwa_install: pwa_install.ServiceClient
    public readonly pwa_stats: pwa_stats.ServiceClient
    public readonly shortener: shortener.ServiceClient
    public readonly sources: sources.ServiceClient
    public readonly user: user.ServiceClient
    public readonly vision: vision.ServiceClient
    public readonly web: web.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.ai_analysis = new ai_analysis.ServiceClient(base)
        this.ai_history = new ai_history.ServiceClient(base)
        this.ai_text_detector = new ai_text_detector.ServiceClient(base)
        this.au_tax = new au_tax.ServiceClient(base)
        this.auth = new auth.ServiceClient(base)
        this.blog = new blog.ServiceClient(base)
        this.blogV2 = new blogV2.ServiceClient(base)
        this.calc_history = new calc_history.ServiceClient(base)
        this.caption_gen = new caption_gen.ServiceClient(base)
        this.compatibility = new compatibility.ServiceClient(base)
        this.exchange = new exchange.ServiceClient(base)
        this.health = new health.ServiceClient(base)
        this.pageviews = new pageviews.ServiceClient(base)
        this.pwa_install = new pwa_install.ServiceClient(base)
        this.pwa_stats = new pwa_stats.ServiceClient(base)
        this.shortener = new shortener.ServiceClient(base)
        this.sources = new sources.ServiceClient(base)
        this.user = new user.ServiceClient(base)
        this.vision = new vision.ServiceClient(base)
        this.web = new web.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * Import the auth handler to be able to derive the auth type
 */
import type { auth as auth_auth } from "~backend/auth/auth";

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    /**
     * Allows you to set the authentication data to be used for each
     * request either by passing in a static object or by passing in
     * a function which returns a new object for each request.
     */
    auth?: RequestType<typeof auth_auth> | AuthDataGenerator
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { analyze as api_ai_analysis_analyze_analyze } from "~backend/ai-analysis/analyze";

export namespace ai_analysis {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.analyze = this.analyze.bind(this)
        }

        /**
         * Analyzes calculator results and provides personalized recommendations across all calculator types
         * Supports financial, regional (US/UK/India/Australia), health, math, and utility calculators
         */
        public async analyze(params: RequestType<typeof api_ai_analysis_analyze_analyze>): Promise<ResponseType<typeof api_ai_analysis_analyze_analyze>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/analyze`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_analysis_analyze_analyze>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { list as api_ai_history_list_list } from "~backend/ai-history/list";
import { save as api_ai_history_save_save } from "~backend/ai-history/save";

export namespace ai_history {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.list = this.list.bind(this)
            this.save = this.save.bind(this)
        }

        public async list(params: RequestType<typeof api_ai_history_list_list>): Promise<ResponseType<typeof api_ai_history_list_list>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                analysisType:   params.analysisType,
                calculatorName: params.calculatorName,
                limit:          params.limit === undefined ? undefined : String(params.limit),
                offset:         params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai-history`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_history_list_list>
        }

        public async save(params: RequestType<typeof api_ai_history_save_save>): Promise<ResponseType<typeof api_ai_history_save_save>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai-history`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_history_save_save>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { detect as api_ai_text_detector_detect_detect } from "~backend/ai-text-detector/detect";

export namespace ai_text_detector {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.detect = this.detect.bind(this)
        }

        public async detect(params: RequestType<typeof api_ai_text_detector_detect_detect>): Promise<ResponseType<typeof api_ai_text_detector_detect_detect>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai-text-detector/detect`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_text_detector_detect_detect>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { bonusWithholding as api_au_tax_bonus_withholding_bonusWithholding } from "~backend/au-tax/bonus_withholding";
import { calculate as api_au_tax_calculate_calculate } from "~backend/au-tax/calculate";
import { leaveWithholding as api_au_tax_leave_withholding_leaveWithholding } from "~backend/au-tax/leave_withholding";
import { studentLoanProjection as api_au_tax_student_loan_projection_studentLoanProjection } from "~backend/au-tax/student_loan_projection";

export namespace au_tax {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.bonusWithholding = this.bonusWithholding.bind(this)
            this.calculate = this.calculate.bind(this)
            this.leaveWithholding = this.leaveWithholding.bind(this)
            this.studentLoanProjection = this.studentLoanProjection.bind(this)
        }

        public async bonusWithholding(params: RequestType<typeof api_au_tax_bonus_withholding_bonusWithholding>): Promise<ResponseType<typeof api_au_tax_bonus_withholding_bonusWithholding>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/au/bonus/withholding`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_au_tax_bonus_withholding_bonusWithholding>
        }

        public async calculate(params: RequestType<typeof api_au_tax_calculate_calculate>): Promise<ResponseType<typeof api_au_tax_calculate_calculate>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/au/paycalc/estimate`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_au_tax_calculate_calculate>
        }

        public async leaveWithholding(params: RequestType<typeof api_au_tax_leave_withholding_leaveWithholding>): Promise<ResponseType<typeof api_au_tax_leave_withholding_leaveWithholding>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/au/leave/withholding`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_au_tax_leave_withholding_leaveWithholding>
        }

        public async studentLoanProjection(params: RequestType<typeof api_au_tax_student_loan_projection_studentLoanProjection>): Promise<ResponseType<typeof api_au_tax_student_loan_projection_studentLoanProjection>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/au/student-loan/projection`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_au_tax_student_loan_projection_studentLoanProjection>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { login as api_auth_login_login } from "~backend/auth/login";

export namespace auth {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.login = this.login.bind(this)
        }

        public async login(params: RequestType<typeof api_auth_login_login>): Promise<ResponseType<typeof api_auth_login_login>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/admin/login`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_login_login>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_blog_create_create } from "~backend/blog/create";
import { remove as api_blog_delete_remove } from "~backend/blog/delete";
import { get as api_blog_get_get } from "~backend/blog/get";
import { list as api_blog_list_list } from "~backend/blog/list";
import { update as api_blog_update_update } from "~backend/blog/update";

export namespace blog {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.get = this.get.bind(this)
            this.list = this.list.bind(this)
            this.remove = this.remove.bind(this)
            this.update = this.update.bind(this)
        }

        public async create(params: RequestType<typeof api_blog_create_create>): Promise<ResponseType<typeof api_blog_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/blog`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_blog_create_create>
        }

        public async get(params: { slug: string }): Promise<ResponseType<typeof api_blog_get_get>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/blog/${encodeURIComponent(params.slug)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_blog_get_get>
        }

        public async list(params: RequestType<typeof api_blog_list_list>): Promise<ResponseType<typeof api_blog_list_list>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:     params.limit === undefined ? undefined : String(params.limit),
                offset:    params.offset === undefined ? undefined : String(params.offset),
                published: params.published === undefined ? undefined : String(params.published),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/blog`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_blog_list_list>
        }

        public async remove(params: { slug: string }): Promise<ResponseType<typeof api_blog_delete_remove>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/blog/${encodeURIComponent(params.slug)}`, {method: "DELETE", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_blog_delete_remove>
        }

        public async update(params: RequestType<typeof api_blog_update_update>): Promise<ResponseType<typeof api_blog_update_update>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                author:    params.author,
                content:   params.content,
                excerpt:   params.excerpt,
                published: params.published,
                title:     params.title,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/blog/${encodeURIComponent(params.slug)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_blog_update_update>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { deleteBlog as api_blogV2_delete_blog_deleteBlog } from "~backend/blog-v2/delete_blog";
import { generate as api_blogV2_generate_generate } from "~backend/blog-v2/generate";
import {
    generateNow as api_blogV2_generate_now_generateNow,
    getProgress as api_blogV2_generate_now_getProgress
} from "~backend/blog-v2/generate_now";
import { getBySlug as api_blogV2_get_by_slug_getBySlug } from "~backend/blog-v2/get_by_slug";
import { getSettings as api_blogV2_get_settings_getSettings } from "~backend/blog-v2/get_settings";
import { list as api_blogV2_list_list } from "~backend/blog-v2/list";
import { listUnbloggedSources as api_blogV2_list_unblogged_sources_listUnbloggedSources } from "~backend/blog-v2/list_unblogged_sources";
import {
    manualGenerateBlog as api_blogV2_manual_trigger_manualGenerateBlog,
    manualSyncSources as api_blogV2_manual_trigger_manualSyncSources
} from "~backend/blog-v2/manual_trigger";
import { testAutoBlogNow as api_blogV2_test_cron_testAutoBlogNow } from "~backend/blog-v2/test_cron";
import { testGenerate as api_blogV2_test_generate_testGenerate } from "~backend/blog-v2/test_generate";
import { update as api_blogV2_update_update } from "~backend/blog-v2/update";
import { updateSettings as api_blogV2_update_settings_updateSettings } from "~backend/blog-v2/update_settings";
import { updateStatus as api_blogV2_update_status_updateStatus } from "~backend/blog-v2/update_status";

export namespace blogV2 {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.deleteBlog = this.deleteBlog.bind(this)
            this.generate = this.generate.bind(this)
            this.generateNow = this.generateNow.bind(this)
            this.getBySlug = this.getBySlug.bind(this)
            this.getProgress = this.getProgress.bind(this)
            this.getSettings = this.getSettings.bind(this)
            this.list = this.list.bind(this)
            this.listUnbloggedSources = this.listUnbloggedSources.bind(this)
            this.manualGenerateBlog = this.manualGenerateBlog.bind(this)
            this.manualSyncSources = this.manualSyncSources.bind(this)
            this.testAutoBlogNow = this.testAutoBlogNow.bind(this)
            this.testGenerate = this.testGenerate.bind(this)
            this.update = this.update.bind(this)
            this.updateSettings = this.updateSettings.bind(this)
            this.updateStatus = this.updateStatus.bind(this)
        }

        public async deleteBlog(params: RequestType<typeof api_blogV2_delete_blog_deleteBlog>): Promise<ResponseType<typeof api_blogV2_delete_blog_deleteBlog>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/blog-v2/delete`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_blogV2_delete_blog_deleteBlog>
        }

        public async generate(params: RequestType<typeof api_blogV2_generate_generate>): Promise<ResponseType<typeof api_blogV2_generate_generate>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/blog-v2/generate`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_blogV2_generate_generate>
        }

        public async generateNow(): Promise<ResponseType<typeof api_blogV2_generate_now_generateNow>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/blog-v2/generate-now`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_blogV2_generate_now_generateNow>
        }

        public async getBySlug(params: { slug: string }): Promise<ResponseType<typeof api_blogV2_get_by_slug_getBySlug>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/blog-v2/${encodeURIComponent(params.slug)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_blogV2_get_by_slug_getBySlug>
        }

        public async getProgress(): Promise<ResponseType<typeof api_blogV2_generate_now_getProgress>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/blog-v2/progress`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_blogV2_generate_now_getProgress>
        }

        public async getSettings(): Promise<ResponseType<typeof api_blogV2_get_settings_getSettings>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/blog-v2/settings`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_blogV2_get_settings_getSettings>
        }

        public async list(params: RequestType<typeof api_blogV2_list_list>): Promise<ResponseType<typeof api_blogV2_list_list>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/blog-v2/list`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_blogV2_list_list>
        }

        public async listUnbloggedSources(params: RequestType<typeof api_blogV2_list_unblogged_sources_listUnbloggedSources>): Promise<ResponseType<typeof api_blogV2_list_unblogged_sources_listUnbloggedSources>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/blog-v2/unblogged-sources`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_blogV2_list_unblogged_sources_listUnbloggedSources>
        }

        public async manualGenerateBlog(): Promise<ResponseType<typeof api_blogV2_manual_trigger_manualGenerateBlog>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/blog-v2/manual-generate`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_blogV2_manual_trigger_manualGenerateBlog>
        }

        public async manualSyncSources(): Promise<ResponseType<typeof api_blogV2_manual_trigger_manualSyncSources>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/blog-v2/manual-sync`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_blogV2_manual_trigger_manualSyncSources>
        }

        public async testAutoBlogNow(): Promise<ResponseType<typeof api_blogV2_test_cron_testAutoBlogNow>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/blog-v2/test-auto-blog`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_blogV2_test_cron_testAutoBlogNow>
        }

        public async testGenerate(): Promise<ResponseType<typeof api_blogV2_test_generate_testGenerate>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/blog-v2/test`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_blogV2_test_generate_testGenerate>
        }

        public async update(params: RequestType<typeof api_blogV2_update_update>): Promise<ResponseType<typeof api_blogV2_update_update>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/blog-v2/update`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_blogV2_update_update>
        }

        public async updateSettings(params: RequestType<typeof api_blogV2_update_settings_updateSettings>): Promise<ResponseType<typeof api_blogV2_update_settings_updateSettings>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/blog-v2/settings/update`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_blogV2_update_settings_updateSettings>
        }

        public async updateStatus(params: RequestType<typeof api_blogV2_update_status_updateStatus>): Promise<ResponseType<typeof api_blogV2_update_status_updateStatus>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/blog-v2/update-status`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_blogV2_update_status_updateStatus>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { deleteEntry as api_calc_history_delete_deleteEntry } from "~backend/calc-history/delete";
import { list as api_calc_history_list_list } from "~backend/calc-history/list";
import { save as api_calc_history_save_save } from "~backend/calc-history/save";
import { update as api_calc_history_update_update } from "~backend/calc-history/update";

export namespace calc_history {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.deleteEntry = this.deleteEntry.bind(this)
            this.list = this.list.bind(this)
            this.save = this.save.bind(this)
            this.update = this.update.bind(this)
        }

        public async deleteEntry(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/calc-history/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        public async list(params: RequestType<typeof api_calc_history_list_list>): Promise<ResponseType<typeof api_calc_history_list_list>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                calculatorType: params.calculatorType,
                favoritesOnly:  params.favoritesOnly === undefined ? undefined : String(params.favoritesOnly),
                limit:          params.limit === undefined ? undefined : String(params.limit),
                offset:         params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/calc-history`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_calc_history_list_list>
        }

        public async save(params: RequestType<typeof api_calc_history_save_save>): Promise<ResponseType<typeof api_calc_history_save_save>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/calc-history`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_calc_history_save_save>
        }

        public async update(params: RequestType<typeof api_calc_history_update_update>): Promise<ResponseType<typeof api_calc_history_update_update>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                favorite: params.favorite,
                notes:    params.notes,
                tags:     params.tags,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/calc-history/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_calc_history_update_update>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { generate as api_caption_gen_generate_generate } from "~backend/caption-gen/generate";

export namespace caption_gen {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.generate = this.generate.bind(this)
        }

        public async generate(params: RequestType<typeof api_caption_gen_generate_generate>): Promise<ResponseType<typeof api_caption_gen_generate_generate>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/caption/generate`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_caption_gen_generate_generate>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { calculate as api_compatibility_calculate_calculate } from "~backend/compatibility/calculate";

export namespace compatibility {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.calculate = this.calculate.bind(this)
        }

        public async calculate(params: RequestType<typeof api_compatibility_calculate_calculate>): Promise<ResponseType<typeof api_compatibility_calculate_calculate>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/compatibility/calculate`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_compatibility_calculate_calculate>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { convert as api_exchange_convert_convert } from "~backend/exchange/convert";
import { getCurrencies as api_exchange_get_currencies_getCurrencies } from "~backend/exchange/get_currencies";
import { getRate as api_exchange_get_rate_getRate } from "~backend/exchange/get_rate";
import { getRates as api_exchange_get_rates_getRates } from "~backend/exchange/get_rates";

export namespace exchange {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.convert = this.convert.bind(this)
            this.getCurrencies = this.getCurrencies.bind(this)
            this.getRate = this.getRate.bind(this)
            this.getRates = this.getRates.bind(this)
        }

        /**
         * Converts an amount from one currency to another.
         */
        public async convert(params: { _from: string, to: string, amount: number }): Promise<ResponseType<typeof api_exchange_convert_convert>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/exchange/convert/${encodeURIComponent(params._from)}/${encodeURIComponent(params.to)}/${encodeURIComponent(params.amount)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_exchange_convert_convert>
        }

        /**
         * Gets a list of supported currencies with their details - 170+ world currencies
         */
        public async getCurrencies(): Promise<ResponseType<typeof api_exchange_get_currencies_getCurrencies>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/exchange/currencies`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_exchange_get_currencies_getCurrencies>
        }

        /**
         * Gets the exchange rate between two currencies.
         */
        public async getRate(params: { _from: string, to: string }): Promise<ResponseType<typeof api_exchange_get_rate_getRate>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/exchange/rate/${encodeURIComponent(params._from)}/${encodeURIComponent(params.to)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_exchange_get_rate_getRate>
        }

        /**
         * Gets exchange rates for multiple currencies against a base currency.
         */
        public async getRates(params: RequestType<typeof api_exchange_get_rates_getRates>): Promise<ResponseType<typeof api_exchange_get_rates_getRates>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                currencies: params.currencies?.map((v) => v),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/exchange/rates/${encodeURIComponent(params.base)}`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_exchange_get_rates_getRates>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    dbHealth as api_health_check_dbHealth,
    root as api_health_check_root,
    status as api_health_check_status
} from "~backend/health/check";

export namespace health {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.dbHealth = this.dbHealth.bind(this)
            this.root = this.root.bind(this)
            this.status = this.status.bind(this)
        }

        public async dbHealth(): Promise<ResponseType<typeof api_health_check_dbHealth>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/health/db`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_health_check_dbHealth>
        }

        public async root(): Promise<ResponseType<typeof api_health_check_root>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_health_check_root>
        }

        public async status(): Promise<ResponseType<typeof api_health_check_status>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/status`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_health_check_status>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getStats as api_pageviews_get_stats_getStats } from "~backend/pageviews/get_stats";
import { track as api_pageviews_track_track } from "~backend/pageviews/track";

export namespace pageviews {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getStats = this.getStats.bind(this)
            this.track = this.track.bind(this)
        }

        public async getStats(): Promise<ResponseType<typeof api_pageviews_get_stats_getStats>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/pageviews/stats`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_pageviews_get_stats_getStats>
        }

        public async track(params: RequestType<typeof api_pageviews_track_track>): Promise<ResponseType<typeof api_pageviews_track_track>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/pageviews/track`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_pageviews_track_track>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getStats as api_pwa_install_get_stats_getStats } from "~backend/pwa-install/get_stats";
import { track as api_pwa_install_track_track } from "~backend/pwa-install/track";

export namespace pwa_install {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getStats = this.getStats.bind(this)
            this.track = this.track.bind(this)
        }

        public async getStats(): Promise<ResponseType<typeof api_pwa_install_get_stats_getStats>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/pwa-install/stats`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_pwa_install_get_stats_getStats>
        }

        public async track(params: RequestType<typeof api_pwa_install_track_track>): Promise<ResponseType<typeof api_pwa_install_track_track>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/pwa-install/track`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_pwa_install_track_track>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getStats as api_pwa_stats_get_stats_getStats } from "~backend/pwa-stats/get_stats";
import { track as api_pwa_stats_track_track } from "~backend/pwa-stats/track";

export namespace pwa_stats {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getStats = this.getStats.bind(this)
            this.track = this.track.bind(this)
        }

        public async getStats(): Promise<ResponseType<typeof api_pwa_stats_get_stats_getStats>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/pwa-stats/stats`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_pwa_stats_get_stats_getStats>
        }

        public async track(params: RequestType<typeof api_pwa_stats_track_track>): Promise<ResponseType<typeof api_pwa_stats_track_track>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/pwa-stats/track`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_pwa_stats_track_track>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { analytics as api_shortener_analytics_analytics } from "~backend/shortener/analytics";
import { create as api_shortener_create_create } from "~backend/shortener/create";
import { redirect as api_shortener_redirect_redirect } from "~backend/shortener/redirect";

export namespace shortener {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.analytics = this.analytics.bind(this)
            this.create = this.create.bind(this)
            this.redirect = this.redirect.bind(this)
        }

        public async analytics(params: { shortCode: string }): Promise<ResponseType<typeof api_shortener_analytics_analytics>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/shortener/analytics/${encodeURIComponent(params.shortCode)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_shortener_analytics_analytics>
        }

        public async create(params: RequestType<typeof api_shortener_create_create>): Promise<ResponseType<typeof api_shortener_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/shortener/create`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_shortener_create_create>
        }

        public async redirect(params: { shortCode: string }): Promise<ResponseType<typeof api_shortener_redirect_redirect>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/shortener/redirect/${encodeURIComponent(params.shortCode)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_shortener_redirect_redirect>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { discover as api_sources_discover_discover } from "~backend/sources/discover";

export namespace sources {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.discover = this.discover.bind(this)
        }

        public async discover(): Promise<ResponseType<typeof api_sources_discover_discover>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/sources/discover`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sources_discover_discover>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getOrCreate as api_user_get_or_create_getOrCreate } from "~backend/user/get_or_create";
import { updatePreferences as api_user_update_preferences_updatePreferences } from "~backend/user/update_preferences";

export namespace user {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getOrCreate = this.getOrCreate.bind(this)
            this.updatePreferences = this.updatePreferences.bind(this)
        }

        public async getOrCreate(): Promise<ResponseType<typeof api_user_get_or_create_getOrCreate>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/user/me`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_user_get_or_create_getOrCreate>
        }

        public async updatePreferences(params: RequestType<typeof api_user_update_preferences_updatePreferences>): Promise<ResponseType<typeof api_user_update_preferences_updatePreferences>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/user/preferences`, {method: "PUT", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_user_update_preferences_updatePreferences>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { analyze as api_vision_analyze_analyze } from "~backend/vision/analyze";
import { analyzeDecorStyle as api_vision_decor_analyzeDecorStyle } from "~backend/vision/decor";
import { getNutrition as api_vision_nutrition_getNutrition } from "~backend/vision/nutrition";
import { analyzePetBreed as api_vision_pet_analyzePetBreed } from "~backend/vision/pet";
import { analyzePlant as api_vision_plant_analyzePlant } from "~backend/vision/plant";

export namespace vision {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.analyze = this.analyze.bind(this)
            this.analyzeDecorStyle = this.analyzeDecorStyle.bind(this)
            this.analyzePetBreed = this.analyzePetBreed.bind(this)
            this.analyzePlant = this.analyzePlant.bind(this)
            this.getNutrition = this.getNutrition.bind(this)
        }

        public async analyze(params: RequestType<typeof api_vision_analyze_analyze>): Promise<ResponseType<typeof api_vision_analyze_analyze>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/vision/analyze`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_vision_analyze_analyze>
        }

        public async analyzeDecorStyle(params: RequestType<typeof api_vision_decor_analyzeDecorStyle>): Promise<ResponseType<typeof api_vision_decor_analyzeDecorStyle>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/vision/decor-style`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_vision_decor_analyzeDecorStyle>
        }

        public async analyzePetBreed(params: RequestType<typeof api_vision_pet_analyzePetBreed>): Promise<ResponseType<typeof api_vision_pet_analyzePetBreed>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/vision/pet-breed`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_vision_pet_analyzePetBreed>
        }

        public async analyzePlant(params: RequestType<typeof api_vision_plant_analyzePlant>): Promise<ResponseType<typeof api_vision_plant_analyzePlant>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/vision/plant`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_vision_plant_analyzePlant>
        }

        public async getNutrition(params: RequestType<typeof api_vision_nutrition_getNutrition>): Promise<ResponseType<typeof api_vision_nutrition_getNutrition>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/vision/nutrition`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_vision_nutrition_getNutrition>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getShortUrl as api_web_shortener_redirect_getShortUrl } from "~backend/web/shortener_redirect";

export namespace web {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.adsPubTxt = this.adsPubTxt.bind(this)
            this.adsTxtRedirect = this.adsTxtRedirect.bind(this)
            this.adsenseScript = this.adsenseScript.bind(this)
            this.adsenseVerificationHtml = this.adsenseVerificationHtml.bind(this)
            this.adsenseVerificationHtmlAlt = this.adsenseVerificationHtmlAlt.bind(this)
            this.canonicalRedirect = this.canonicalRedirect.bind(this)
            this.domainStatus = this.domainStatus.bind(this)
            this.getShortUrl = this.getShortUrl.bind(this)
            this.robots = this.robots.bind(this)
            this.sitemap = this.sitemap.bind(this)
        }

        public async adsPubTxt(options: PickMethods<"GET"> = {}): Promise<globalThis.Response> {
            options.method ||= "GET";
            return this.baseClient.callAPI(`/ads-ca-pub-7271075626732183.txt`, options)
        }

        /**
         * Redirects ads.txt to Ezoic Ads.txt Manager
         */
        public async adsTxtRedirect(options: PickMethods<"GET"> = {}): Promise<globalThis.Response> {
            options.method ||= "GET";
            return this.baseClient.callAPI(`/ads.txt`, options)
        }

        /**
         * Serves a minimal HTML page with just the AdSense script for verification
         */
        public async adsenseScript(options: PickMethods<"GET"> = {}): Promise<globalThis.Response> {
            options.method ||= "GET";
            return this.baseClient.callAPI(`/ads-verification.html`, options)
        }

        /**
         * Serves AdSense verification HTML page
         */
        public async adsenseVerificationHtml(options: PickMethods<"GET"> = {}): Promise<globalThis.Response> {
            options.method ||= "GET";
            return this.baseClient.callAPI(`/adsense-verification`, options)
        }

        public async adsenseVerificationHtmlAlt(options: PickMethods<"GET"> = {}): Promise<globalThis.Response> {
            options.method ||= "GET";
            return this.baseClient.callAPI(`/adsense-verification.html`, options)
        }

        /**
         * Handle www to non-www redirect (or vice versa) based on canonical domain
         */
        public async canonicalRedirect(options: PickMethods<"GET" | "HEAD"> = {}): Promise<globalThis.Response> {
            options.method ||= "GET";
            return this.baseClient.callAPI(`/redirect-check`, options)
        }

        /**
         * Status check for domain canonicalization
         */
        public async domainStatus(options: PickMethods<"GET"> = {}): Promise<globalThis.Response> {
            options.method ||= "GET";
            return this.baseClient.callAPI(`/domain-status`, options)
        }

        public async getShortUrl(params: { shortCode: string }): Promise<ResponseType<typeof api_web_shortener_redirect_getShortUrl>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/s/${encodeURIComponent(params.shortCode)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_web_shortener_redirect_getShortUrl>
        }

        public async robots(options: PickMethods<"GET"> = {}): Promise<globalThis.Response> {
            options.method ||= "GET";
            return this.baseClient.callAPI(`/robots.txt`, options)
        }

        public async sitemap(options: PickMethods<"GET"> = {}): Promise<globalThis.Response> {
            options.method ||= "GET";
            return this.baseClient.callAPI(`/sitemap.xml`, options)
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}

// AuthDataGenerator is a function that returns a new instance of the authentication data required by this API
export type AuthDataGenerator = () =>
  | RequestType<typeof auth_auth>
  | Promise<RequestType<typeof auth_auth> | undefined>
  | undefined;

// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
    readonly authGenerator?: AuthDataGenerator

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "-Generated-TS-Client (Encore/1.50.6)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }

        // Setup an authentication data generator using the auth data token option
        if (options.auth !== undefined) {
            const auth = options.auth
            if (typeof auth === "function") {
                this.authGenerator = auth
            } else {
                this.authGenerator = () => auth
            }
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        let authData: RequestType<typeof auth_auth> | undefined;

        // If authorization data generator is present, call it and add the returned data to the request
        if (this.authGenerator) {
            const mayBePromise = this.authGenerator();
            if (mayBePromise instanceof Promise) {
                authData = await mayBePromise;
            } else {
                authData = mayBePromise;
            }
        }

        if (authData) {
            const data: CallParameters = {};

            data.headers = makeRecord<string, string>({
                authorization: authData.authorization,
            });

            return data;
        }

        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

export default new Client(import.meta.env.VITE_CLIENT_TARGET, { requestInit: { credentials: "include" } });
