// Type overrides for lucide-react
declare module 'lucide-react' {
  import { FC, SVGProps } from 'react';
  
  export interface LucideProps extends Partial<Omit<SVGProps<SVGSVGElement>, 'ref'>> {
    size?: string | number;
    absoluteStrokeWidth?: boolean;
    className?: string;
  }

  export type LucideIcon = FC<LucideProps>;

  // Export all commonly used icons
  export const Calculator: LucideIcon;
  export const Menu: LucideIcon;
  export const ChevronDown: LucideIcon;
  export const ChevronUp: LucideIcon;
  export const ChevronRight: LucideIcon;
  export const History: LucideIcon;
  export const Search: LucideIcon;
  export const X: LucideIcon;
  export const Home: LucideIcon;
  export const Shield: LucideIcon;
  export const Flame: LucideIcon;
  export const Clock: LucideIcon;
  export const Wrench: LucideIcon;
  export const Bot: LucideIcon;
  export const Loader2: LucideIcon;
  export const Brain: LucideIcon;
  export const TrendingUp: LucideIcon;
  export const TrendingDown: LucideIcon;
  export const AlertTriangle: LucideIcon;
  export const Target: LucideIcon;
  export const CheckCircle: LucideIcon;
  export const Lock: LucideIcon;
  export const ExternalLink: LucideIcon;
  export const DollarSign: LucideIcon;
  export const Heart: LucideIcon;
  export const Calculator: LucideIcon;
  export const Info: LucideIcon;
  export const AlertCircle: LucideIcon;
  export const FileText: LucideIcon;
  export const Twitter: LucideIcon;
  export const Linkedin: LucideIcon;
  export const Facebook: LucideIcon;
  export const Link: LucideIcon;
  export const Share2: LucideIcon;
  export const Download: LucideIcon;
  export const DogIcon: LucideIcon;
  export const CatIcon: LucideIcon;
  export const Building2: LucideIcon;
  export const Users: LucideIcon;
  export const Cookie: LucideIcon;
  export const ArrowRight: LucideIcon;
  export const Check: LucideIcon;
  export const Minus: LucideIcon;
  export const Plus: LucideIcon;
  export const Activity: LucideIcon;
  export const Award: LucideIcon;
  export const BarChart: LucideIcon;
  export const Zap: LucideIcon;
  export const Lightbulb: LucideIcon;
  export const Sparkles: LucideIcon;
  export const Calendar: LucideIcon;
  export const Settings: LucideIcon;
  export const Globe: LucideIcon;
  export const MapPin: LucideIcon;
  export const Wifi: LucideIcon;
  export const WifiOff: LucideIcon;
  export const RefreshCw: LucideIcon;
  export const ArrowUpDown: LucideIcon;
  export const Pizza: LucideIcon;
  export const ShieldAlert: LucideIcon;
  export const ZapIcon: LucideIcon;
  export const ArrowLeft: LucideIcon;
  export const BookOpen: LucideIcon;
  export const HelpCircle: LucideIcon;
  export const Bold: LucideIcon;
  export const Italic: LucideIcon;
  export const List: LucideIcon;
  export const ListOrdered: LucideIcon;
  export const Image: LucideIcon;
  export const Code: LucideIcon;
  export const Quote: LucideIcon;
  export const Camera: LucideIcon;
  export const Upload: LucideIcon;
  export const Smartphone: LucideIcon;
  export const Eye: LucideIcon;
  export const Copy: LucideIcon;
  export const MessageCircle: LucideIcon;
  export const Instagram: LucideIcon;
  export const Type: LucideIcon;
  export const Heading1: LucideIcon;
  export const Heading2: LucideIcon;
  export const Heading3: LucideIcon;
  export const Send: LucideIcon;
  export const Mail: LucideIcon;
  export const Phone: LucideIcon;
  export const Edit: LucideIcon;
  export const Trash: LucideIcon;
  export const Save: LucideIcon;
  export const Filter: LucideIcon;
  export const SortAsc: LucideIcon;
  export const SortDesc: LucideIcon;
  export const MoreVertical: LucideIcon;
  export const MoreHorizontal: LucideIcon;
  export const ChevronLeft: LucideIcon;
  export const Play: LucideIcon;
  export const Pause: LucideIcon;
  export const StopCircle: LucideIcon;
  export const RotateCcw: LucideIcon;
  export const Timer: LucideIcon;
  export const GitBranch: LucideIcon;
  export const Link2: LucideIcon;
  export const BarChart3: LucideIcon;
  export const Star: LucideIcon;
  export const Trash2: LucideIcon;
  export const Tag: LucideIcon;
  export const Car: LucideIcon;
  export const Wallet: LucideIcon;
  export const Palmtree: LucideIcon;
  export const Bug: LucideIcon;
  export const Monitor: LucideIcon;
  export const Gauge: LucideIcon;
  export const Network: LucideIcon;
  export const Rocket: LucideIcon;
  export const LogOut: LucideIcon;
  export const CheckIcon: LucideIcon;
  export const XIcon: LucideIcon;
  export const CircleIcon: LucideIcon;
  export const ChevronRightIcon: LucideIcon;
  export const ChevronDownIcon: LucideIcon;
  export const ChevronUpIcon: LucideIcon;
  export const XCircle: LucideIcon;
  export const Skull: LucideIcon;
  export const Baby: LucideIcon;
  export const Sparkle: LucideIcon;
  export const ShoppingBag: LucideIcon;
  export const Gift: LucideIcon;
  export const CheckCircle2: LucideIcon;
  export const Palette: LucideIcon;

  // Add more as needed...
  const icons: Record<string, LucideIcon>;
  export default icons;
}

