// @ts-nocheck
import { useState, useMemo, useEffect } from 'react';
import { Search, X, Activity, DollarSign, Wrench, Home, Globe, Heart, Shield, Users, Bot, Sparkles, Calculator as CalculatorIcon, Wifi, Clock, FileText, Info } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import { Link } from 'react-router-dom';
import backend from '~backend/client';

interface Calculator {
  name: string;
  path: string;
  category: string;
  icon: React.ComponentType<{ className?: string }>;
  keywords?: string[];
  isAutoGenerated?: boolean;
}

const ALL_CALCULATORS: Calculator[] = [
  { name: 'BMI Calculator', path: '/calculator/bmi', category: 'Health', icon: Activity, keywords: ['body', 'mass', 'index', 'weight', 'height'] },
  { name: 'Body Fat Calculator', path: '/calculators/health/body-fat', category: 'Health', icon: Activity, keywords: ['body fat', 'percentage', 'navy method', 'circumference', 'lean mass', 'fat mass'] },
  { name: 'BMR & TDEE Calculator', path: '/calculators/health/bmr', category: 'Health', icon: Activity, keywords: ['bmr', 'tdee', 'basal metabolic rate', 'calories', 'energy', 'mifflin'] },
  { name: 'Ideal Weight Calculator', path: '/calculators/health/ideal-weight', category: 'Health', icon: Activity, keywords: ['ideal weight', 'devine', 'hamwi', 'robinson', 'miller', 'target weight'] },

  { name: 'Water Intake Calculator', path: '/calculators/health/water-intake', category: 'Health', icon: Activity, keywords: ['water', 'hydration', 'intake', 'fluid', 'daily water'] },
  { name: 'Weight Loss Step Calculator', path: '/calculator/weight-loss-steps', category: 'Health', icon: Activity, keywords: ['fitness', 'walking', 'exercise'] },
  { name: 'Waist to Hip Ratio Calculator', path: '/calculator/waist-to-hip-ratio', category: 'Health', icon: Activity, keywords: ['whr', 'body shape', 'health risk', 'waist', 'hip', 'ratio', 'who', 'cardiovascular', 'obesity'] },
  { name: 'Sleep Cycle Calculator', path: '/calculators/health/sleep', category: 'Health', icon: Activity, keywords: ['sleep', 'cycle', 'bedtime', 'wake time', 'rem', 'nrem', 'sleep quality'] },
  { name: 'Heart Rate Zone Calculator', path: '/calculators/health/heart-rate-zone', category: 'Health', icon: Activity, keywords: ['heart rate', 'zone', 'training', 'cardio', 'karvonen', 'max hr', 'bpm'] },
  { name: 'Pregnancy Due Date Calculator', path: '/calculators/health/pregnancy-due-date', category: 'Health', icon: Activity, keywords: ['pregnancy', 'due date', 'edd', 'lmp', 'naegele', 'trimester', 'gestational age'] },
  { name: 'Ovulation Calculator', path: '/calculators/health/ovulation', category: 'Health', icon: Activity, keywords: ['ovulation', 'fertile window', 'fertility', 'period', 'cycle', 'conception'] },
  
  { name: 'Investment Calculator', path: '/calculator/investment', category: 'Finance', icon: DollarSign, keywords: ['money', 'stocks', 'portfolio', 'returns'] },
  { name: 'Simple Interest Calculator', path: '/calculator/simple-interest', category: 'Finance', icon: DollarSign, keywords: ['loan', 'interest', 'rate'] },
  { name: 'Compound Interest Calculator', path: '/calculator/compound-interest', category: 'Finance', icon: DollarSign, keywords: ['savings', 'growth', 'interest'] },
  { name: 'ROI Calculator', path: '/calculator/roi', category: 'Finance', icon: DollarSign, keywords: ['return', 'investment', 'profit'] },
  { name: 'Retirement Calculator', path: '/calculator/retirement', category: 'Finance', icon: DollarSign, keywords: ['pension', 'savings', 'future'] },
  { name: 'Credit Card Payoff Calculator', path: '/calculator/credit-card-payoff', category: 'Finance', icon: DollarSign, keywords: ['debt', 'payment', 'balance'] },
  { name: 'Emergency Fund Calculator', path: '/calculator/emergency-fund', category: 'Finance', icon: DollarSign, keywords: ['savings', 'rainy day', 'emergency'] },
  { name: 'Paycheck Calculator', path: '/calculator/paycheck', category: 'Finance', icon: DollarSign, keywords: ['salary', 'tax', 'deductions'] },
  { name: 'Salary Calculator', path: '/calculator/salary', category: 'Finance', icon: DollarSign, keywords: ['money', 'income', 'wage'] },
  { name: 'Profit Margin Calculator', path: '/calculator/profit-margin', category: 'Finance', icon: DollarSign, keywords: ['business', 'profit', 'revenue'] },
  
  { name: 'Percentage Calculator', path: '/calculator/percentage', category: 'Math', icon: CalculatorIcon, keywords: ['percent', 'ratio', 'fraction'] },
  { name: 'Age Calculator', path: '/calculator/age', category: 'Math', icon: CalculatorIcon, keywords: ['birthday', 'years', 'date'] },
  { name: 'Unit Converter', path: '/calculator/unit-converter', category: 'Math', icon: CalculatorIcon, keywords: ['convert', 'measurement', 'metric'] },
  { name: 'Scientific Calculator', path: '/calculator/scientific', category: 'Math', icon: CalculatorIcon, keywords: ['scientific', 'calculator', 'advanced', 'math', 'functions'] },
  { name: 'Fraction Calculator', path: '/calculator/fraction', category: 'Math', icon: CalculatorIcon, keywords: ['fraction', 'calculator', 'math', 'division'] },
  { name: 'Statistics Calculator', path: '/calculator/statistics', category: 'Math', icon: CalculatorIcon, keywords: ['statistics', 'mean', 'median', 'mode', 'math', 'data'] },
  
  { name: 'Tip Calculator', path: '/calculator/tip', category: 'Utility', icon: Wrench, keywords: ['restaurant', 'gratuity', 'service'] },
  { name: 'Currency Converter', path: '/calculator/currency-converter', category: 'Utility', icon: Wrench, keywords: ['money', 'exchange', 'forex'] },
  { name: 'Discount Calculator', path: '/calculator/discount', category: 'Utility', icon: Wrench, keywords: ['sale', 'savings', 'price', 'reduction'] },
  { name: 'Date Calculator', path: '/calculator/date', category: 'Utility', icon: Wrench, keywords: ['time', 'days', 'duration', 'calendar'] },
  { name: 'Password Generator', path: '/calculator/password-generator', category: 'Utility', icon: Wrench, keywords: ['security', 'random', 'strong password'] },
  
  { name: 'Mortgage Calculator', path: '/calculator/mortgage', category: 'US', icon: Home, keywords: ['home', 'loan', 'property', 'house'] },
  { name: 'Loan Calculator', path: '/calculator/loan', category: 'US', icon: Home, keywords: ['borrow', 'payment', 'debt'] },
  { name: 'Auto Loan Calculator', path: '/calculator/auto-loan', category: 'US', icon: Home, keywords: ['car', 'vehicle', 'financing'] },
  { name: 'Business Loan Calculator', path: '/calculator/business-loan', category: 'US', icon: Home, keywords: ['commercial', 'company', 'enterprise'] },
  { name: 'Student Loan Calculator', path: '/calculator/student-loan', category: 'US', icon: Home, keywords: ['education', 'college', 'university'] },
  { name: 'HELOC Calculator', path: '/calculator/heloc', category: 'US', icon: Home, keywords: ['home equity', 'line of credit'] },
  { name: 'Debt Consolidation Calculator', path: '/calculator/debt-consolidation', category: 'US', icon: Home, keywords: ['refinance', 'combine'] },
  { name: 'Loan Affordability Calculator', path: '/calculator/loan-affordability', category: 'US', icon: Home, keywords: ['budget', 'qualify'] },
  { name: 'Federal Tax Calculator', path: '/calculator/federal-tax', category: 'US', icon: Home, keywords: ['irs', 'income tax'] },
  { name: 'State Tax Calculator', path: '/calculator/state-tax', category: 'US', icon: Home, keywords: ['income tax', 'state'] },
  { name: '401k Retirement Calculator', path: '/calculator/401k-retirement', category: 'US', icon: Home, keywords: ['retirement', 'pension', '401k'] },
  
  { name: 'Stamp Duty Calculator', path: '/calculators/uk/stamp-duty', category: 'UK', icon: Globe, keywords: ['property', 'tax', 'purchase'] },
  { name: 'ISA Calculator', path: '/calculators/uk/isa', category: 'UK', icon: Globe, keywords: ['savings', 'tax-free'] },
  { name: 'National Insurance Calculator', path: '/calculators/uk/national-insurance', category: 'UK', icon: Globe, keywords: ['ni', 'tax', 'contributions'] },
  { name: 'Pension Calculator', path: '/calculators/uk/pension', category: 'UK', icon: Globe, keywords: ['retirement', 'pension'] },
  { name: 'Buy-to-Let Mortgage Calculator', path: '/calculators/uk/btl-mortgage', category: 'UK', icon: Globe, keywords: ['rental', 'property', 'landlord'] },
  
  { name: 'EPF Calculator', path: '/calculators/india/epf', category: 'India', icon: Globe, keywords: ['provident fund', 'pf'] },
  { name: 'SIP Calculator', path: '/calculators/india/sip', category: 'India', icon: Globe, keywords: ['mutual fund', 'investment'] },
  { name: 'Income Tax Calculator (India)', path: '/calculators/india/income-tax', category: 'India', icon: Globe, keywords: ['tax', 'itr'] },
  { name: 'PPF Calculator', path: '/calculators/india/ppf', category: 'India', icon: Globe, keywords: ['public provident fund', 'savings'] },
  { name: 'Home Loan Calculator (India)', path: '/calculators/india/home-loan', category: 'India', icon: Globe, keywords: ['mortgage', 'property', 'emi'] },
  { name: 'GST Calculator', path: '/calculators/india/gst', category: 'India', icon: Globe, keywords: ['goods', 'services', 'tax'] },
  { name: 'EMI Calculator', path: '/calculators/india/emi', category: 'India', icon: Globe, keywords: ['loan', 'installment', 'emi'] },
  
  { name: 'Superannuation Calculator', path: '/calculators/australia/superannuation', category: 'Australia', icon: Globe, keywords: ['retirement', 'super'] },
  { name: 'Property Tax Calculator (Australia)', path: '/calculators/australia/property-tax', category: 'Australia', icon: Globe, keywords: ['land tax', 'council rates'] },
  { name: 'Capital Gains Tax Calculator', path: '/calculators/australia/cgt', category: 'Australia', icon: Globe, keywords: ['cgt', 'investment', 'property'] },
  { name: 'Fringe Benefits Tax Calculator', path: '/calculators/australia/fbt', category: 'Australia', icon: Globe, keywords: ['fbt', 'employee benefits'] },
  { name: 'Negative Gearing Calculator', path: '/calculators/australia/negative-gearing', category: 'Australia', icon: Globe, keywords: ['property', 'investment', 'tax'] },
  { name: 'First Home Buyer Calculator (NSW)', path: '/calculators/australia/first-home-buyer-nsw', category: 'Australia', icon: Globe, keywords: ['property', 'stamp duty', 'first home'] },
  { name: 'Income Tax Calculator (Australia)', path: '/calculators/australia/income-tax', category: 'Australia', icon: Globe, keywords: ['tax', 'ato'] },
  { name: 'Pay Calculator (Australia)', path: '/au/pay-calculator', category: 'Australia', icon: Globe, keywords: ['pay', 'salary', 'payg', 'tax'] },
  { name: 'Student Loan Calculator (Australia)', path: '/au/student-loan', category: 'Australia', icon: Globe, keywords: ['help', 'hecs', 'student loan', 'education'] },
  { name: 'Bonus Tax Calculator (Australia)', path: '/au/bonus-tax', category: 'Australia', icon: Globe, keywords: ['bonus', 'tax', 'withholding', 'payg', 'commission', 'schedule 5', 'ato'] },
  { name: 'Unused Leave Calculator (Australia)', path: '/au/unused-leave', category: 'Australia', icon: Globe, keywords: ['annual leave', 'leave', 'payout', 'termination'] },
  { name: 'Tax Distribution (Australia)', path: '/au/tax-distribution', category: 'Australia', icon: Globe, keywords: ['tax', 'breakdown', 'distribution', 'ato'] },
  { name: 'Comprehensive Tax Calculator (Australia)', path: '/calculators/australia/comprehensive-tax', category: 'Australia', icon: Globe, keywords: ['tax', 'comprehensive', 'deductions', 'offsets'] },
  
  { name: 'Life Insurance Calculator', path: '/calculators/insurance/life-insurance', category: 'Insurance', icon: Shield, keywords: ['coverage', 'protection', 'life'] },
  { name: 'Health Insurance Calculator', path: '/calculators/insurance/health-insurance', category: 'Insurance', icon: Shield, keywords: ['medical', 'coverage', 'health'] },
  { name: 'Car Insurance Calculator', path: '/calculators/insurance/car-insurance', category: 'Insurance', icon: Shield, keywords: ['auto', 'vehicle', 'coverage'] },
  { name: 'Travel Insurance Calculator', path: '/calculators/insurance/travel', category: 'Insurance', icon: Shield, keywords: ['travel', 'trip', 'vacation', 'coverage', 'insurance'] },
  { name: 'Pet Insurance Calculator', path: '/calculators/insurance/pet', category: 'Insurance', icon: Shield, keywords: ['pet', 'dog', 'cat', 'veterinary', 'insurance'] },
  { name: 'Business Liability Calculator', path: '/calculators/insurance/business-liability', category: 'Insurance', icon: Shield, keywords: ['business', 'liability', 'coverage', 'commercial', 'insurance'] },
  
  { name: 'Legal Settlement Estimator', path: '/calculator/legal-settlement', category: 'Finance', icon: DollarSign, keywords: ['legal', 'lawsuit', 'settlement', 'compensation', 'injury'] },
  { name: 'Solar Savings Calculator', path: '/calculator/solar-savings', category: 'Finance', icon: DollarSign, keywords: ['solar', 'energy', 'savings', 'panels', 'renewable'] },
  { name: 'Car Insurance Premium Estimator', path: '/calculator/car-insurance-premium', category: 'Insurance', icon: Shield, keywords: ['car insurance', 'premium', 'auto', 'quote'] },
  
  { name: 'Love & Compatibility Calculator', path: '/calculator/love-compatibility', category: 'Viral', icon: Heart, keywords: ['romance', 'relationship', 'couple', 'love'] },
  { name: 'Friend Compatibility Calculator', path: '/calculators/viral/friend-compatibility', category: 'Viral', icon: Heart, keywords: ['friendship', 'friends', 'compatibility', 'relationship'] },
  { name: 'Zodiac Compatibility Calculator', path: '/calculators/viral/zodiac-compatibility', category: 'Viral', icon: Heart, keywords: ['zodiac', 'astrology', 'horoscope', 'compatibility', 'signs'] },
  { name: 'Life Path Number Calculator', path: '/calculators/viral/life-path-number', category: 'Viral', icon: Heart, keywords: ['numerology', 'life path', 'destiny', 'spiritual'] },
  { name: 'Life Expectancy Calculator', path: '/calculators/viral/life-expectancy', category: 'Viral', icon: Heart, keywords: ['life expectancy', 'lifespan', 'longevity', 'health'] },
  { name: 'Calorie Burn Calculator', path: '/calculators/viral/calorie-burn', category: 'Viral', icon: Heart, keywords: ['calories', 'burn', 'exercise', 'fitness', 'workout'] },
  { name: 'How Long to Watch Calculator', path: '/calculators/viral/how-long-to-watch', category: 'Viral', icon: Heart, keywords: ['tv show', 'binge watch', 'series', 'time', 'episodes'] },
  
  { name: 'AI Compatibility Calculator', path: '/ai/relationships/compatibility', category: 'AI Tools', icon: Bot, keywords: ['relationship', 'match', 'ai', 'compatibility'] },
  { name: 'Baby Name Generator', path: '/ai/parenting/baby-name-generator', category: 'AI Tools', icon: Bot, keywords: ['baby', 'name', 'parenting', 'generator'] },
  { name: 'Gift Recommender', path: '/ai/shopping/gift-recommender', category: 'AI Tools', icon: Bot, keywords: ['present', 'shopping', 'gift', 'recommend'] },
  { name: 'Hashtag Generator', path: '/ai/social/hashtag-generator', category: 'AI Tools', icon: Bot, keywords: ['social media', 'instagram', 'tags', 'hashtag', 'twitter', 'tiktok'] },
  { name: 'Mood Journal', path: '/ai/wellness/mood-journal', category: 'AI Tools', icon: Bot, keywords: ['mental health', 'wellness', 'emotions', 'journal'] },
  { name: 'Pickup Line Generator', path: '/ai/relationships/pickup-lines', category: 'AI Tools', icon: Bot, keywords: ['flirt', 'dating', 'romance', 'pickup'] },

  { name: 'Instagram Bio Analyzer', path: '/ai/social/instagram-bio-analyzer', category: 'AI Tools', icon: Bot, keywords: ['instagram', 'profile', 'bio', 'analyzer'] },
  { name: 'Profile Analyzer', path: '/ai/social/profile-analyzer', category: 'AI Tools', icon: Bot, keywords: ['social media', 'profile', 'instagram', 'analyzer'] },
  { name: 'TikTok Profile Score', path: '/ai/social/tiktok-profile-score', category: 'AI Tools', icon: Bot, keywords: ['tiktok', 'profile', 'score', 'analyzer'] },
  { name: 'Caption Generator', path: '/ai/social/caption-generator', category: 'AI Tools', icon: Bot, keywords: ['social media', 'instagram', 'caption', 'post', 'content'] },
  { name: 'Audience Analyzer', path: '/ai/social/audience-analyzer', category: 'AI Tools', icon: Bot, keywords: ['social media', 'audience', 'followers', 'analytics'] },
  { name: 'AI Text Detector', path: '/ai/ai-text-detector', category: 'AI Tools', icon: Bot, keywords: ['ai', 'text', 'detector', 'chatgpt', 'content', 'detection', 'plagiarism'] },
  
  { name: 'AI Relationships Hub', path: '/ai/relationships', category: 'AI Hub', icon: Sparkles, keywords: ['relationships', 'ai', 'hub', 'love', 'dating'] },
  { name: 'AI Wellness Hub', path: '/ai/wellness', category: 'AI Hub', icon: Sparkles, keywords: ['wellness', 'ai', 'hub', 'health', 'mental'] },
  { name: 'AI Parenting Hub', path: '/ai/parenting', category: 'AI Hub', icon: Sparkles, keywords: ['parenting', 'ai', 'hub', 'baby', 'family'] },
  { name: 'AI Shopping Hub', path: '/ai/shopping', category: 'AI Hub', icon: Sparkles, keywords: ['shopping', 'ai', 'hub', 'gift', 'recommendations'] },
  { name: 'AI Social Media Hub', path: '/ai/social', category: 'AI Hub', icon: Sparkles, keywords: ['social', 'ai', 'hub', 'instagram', 'tiktok'] },
  
  { name: 'Finance Tools Hub', path: '/finance/tools', category: 'Hub', icon: DollarSign, keywords: ['finance', 'hub', 'tools', 'money', 'calculator'] },
  { name: 'Health Tools Hub', path: '/health/tools', category: 'Hub', icon: Activity, keywords: ['health', 'hub', 'tools', 'fitness', 'wellness'] },
  { name: 'Math Tools Hub', path: '/math/tools', category: 'Hub', icon: CalculatorIcon, keywords: ['math', 'hub', 'tools', 'calculation', 'converter'] },
  { name: 'Utility Tools Hub', path: '/utility/tools', category: 'Hub', icon: Wrench, keywords: ['utility', 'hub', 'tools', 'converter', 'calculator'] },
  { name: 'US Tools Hub', path: '/us/tools', category: 'Hub', icon: Home, keywords: ['us', 'hub', 'tools', 'usa', 'america'] },
  { name: 'UK Tools Hub', path: '/uk/tools', category: 'Hub', icon: Globe, keywords: ['uk', 'hub', 'tools', 'britain', 'england'] },
  { name: 'India Tools Hub', path: '/india/tools', category: 'Hub', icon: Globe, keywords: ['india', 'hub', 'tools', 'indian'] },
  { name: 'Australia Tools Hub', path: '/australia/tools', category: 'Hub', icon: Globe, keywords: ['australia', 'hub', 'tools', 'aussie'] },
  { name: 'Insurance Tools Hub', path: '/insurance/tools', category: 'Hub', icon: Shield, keywords: ['insurance', 'hub', 'tools', 'coverage'] },
  { name: 'Viral Tools Hub', path: '/viral/tools', category: 'Hub', icon: Heart, keywords: ['viral', 'hub', 'tools', 'fun', 'compatibility'] },
  { name: 'Australia Pay & Tax Hub', path: '/au', category: 'Hub', icon: Globe, keywords: ['australia', 'pay', 'tax', 'hub', 'ato', 'salary'] },
  
  { name: 'Know My IP', path: '/tools/knowmyip', category: 'Network Tools', icon: Wifi, keywords: ['ip', 'address', 'network', 'internet', 'location', 'isp'] },
  { name: 'Smart Shortener', path: '/tools/shortener', category: 'Network Tools', icon: Wifi, keywords: ['url', 'shortener', 'link', 'shorten', 'redirect', 'qr'] },
  { name: 'Internet Speed Test', path: '/tools/speed-test', category: 'Network Tools', icon: Wifi, keywords: ['speed', 'internet', 'bandwidth', 'test', 'network', 'download', 'upload'] },
  { name: 'IP Reputation Check', path: '/tools/ip-reputation', category: 'Network Tools', icon: Wifi, keywords: ['ip', 'reputation', 'blacklist', 'security', 'network'] },
  { name: 'SSL Domain Checker', path: '/tools/ssl-checker', category: 'Network Tools', icon: Wifi, keywords: ['ssl', 'certificate', 'https', 'security', 'domain', 'tls'] },
  { name: 'DNS Ping Test', path: '/tools/dns-ping', category: 'Network Tools', icon: Wifi, keywords: ['dns', 'ping', 'network', 'latency', 'test', 'domain'] },
  { name: 'Browser & Device Info', path: '/tools/browser-info', category: 'Network Tools', icon: Wifi, keywords: ['browser', 'device', 'info', 'user agent', 'screen', 'resolution'] },
  
  { name: 'SmartTimer Hub', path: '/smarttimer', category: 'Timer Tools', icon: Clock, keywords: ['timer', 'stopwatch', 'countdown', 'pomodoro', 'time', 'clock'] },
  { name: 'Stopwatch', path: '/smarttimer/stopwatch', category: 'Timer Tools', icon: Clock, keywords: ['stopwatch', 'timer', 'time', 'measure'] },
  { name: 'Countdown Timer', path: '/smarttimer/countdown', category: 'Timer Tools', icon: Clock, keywords: ['countdown', 'timer', 'alarm', 'time'] },
  { name: 'Pomodoro Timer', path: '/smarttimer/pomodoro', category: 'Timer Tools', icon: Clock, keywords: ['pomodoro', 'productivity', 'focus', 'timer', 'work'] },
  { name: 'Multi Timer', path: '/smarttimer/multi-timer', category: 'Timer Tools', icon: Clock, keywords: ['multi', 'timer', 'multiple', 'simultaneous'] },
  { name: 'Event Countdown', path: '/smarttimer/event', category: 'Timer Tools', icon: Clock, keywords: ['event', 'countdown', 'timer', 'date', 'special'] },
  
  { name: 'About Us', path: '/about', category: 'Info Pages', icon: Info, keywords: ['about', 'information', 'company', 'team'] },
  { name: 'Contact', path: '/contact', category: 'Info Pages', icon: Info, keywords: ['contact', 'support', 'help', 'email'] },
  { name: 'Privacy Policy', path: '/privacy', category: 'Info Pages', icon: FileText, keywords: ['privacy', 'policy', 'data', 'protection'] },
  { name: 'Terms of Service', path: '/terms', category: 'Info Pages', icon: FileText, keywords: ['terms', 'service', 'conditions', 'legal'] },
  { name: 'Blog', path: '/blog', category: 'Info Pages', icon: FileText, keywords: ['blog', 'articles', 'news', 'posts'] },
  { name: 'History', path: '/history', category: 'Info Pages', icon: FileText, keywords: ['history', 'calculations', 'saved', 'past'] },
];

interface CalculatorSearchProps {
  variant?: 'navbar' | 'page' | 'mobile';
  onSelect?: () => void;
}

export function CalculatorSearch({ variant = 'navbar', onSelect }: CalculatorSearchProps) {
  const [query, setQuery] = useState('');
  const [open, setOpen] = useState(false);
  const [allCalculators, setAllCalculators] = useState<Calculator[]>(ALL_CALCULATORS);

  useEffect(() => {
    setAllCalculators(ALL_CALCULATORS);
  }, []);

  const filteredCalculators = useMemo(() => {
    if (!query.trim()) return allCalculators;

    const searchTerm = query.toLowerCase().trim();
    return allCalculators.filter(calc => {
      const nameMatch = calc.name.toLowerCase().includes(searchTerm);
      const categoryMatch = calc.category.toLowerCase().includes(searchTerm);
      const keywordMatch = calc.keywords?.some(keyword => 
        keyword.toLowerCase().includes(searchTerm)
      );
      
      return nameMatch || categoryMatch || keywordMatch;
    });
  }, [query, allCalculators]);

  const handleSelect = () => {
    setOpen(false);
    setQuery('');
    onSelect?.();
  };

  if (variant === 'navbar') {
    return (
      <Dialog open={open} onOpenChange={setOpen}>
        <DialogTrigger asChild>
          <Button variant="ghost" size="sm" className="hidden lg:flex items-center space-x-1">
            <Search className="h-4 w-4" />
            <span className="text-sm">Search</span>
          </Button>
        </DialogTrigger>
        <DialogContent className="max-w-2xl max-h-[80vh] overflow-hidden flex flex-col">
          <DialogHeader>
            <DialogTitle>Search Calculators</DialogTitle>
            <DialogDescription>
              Find the perfect calculator for your needs
            </DialogDescription>
          </DialogHeader>
          
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <Input
              placeholder="Search by name, category, or keyword..."
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              className="pl-10 pr-10"
              autoFocus
            />
            {query && (
              <Button
                variant="ghost"
                size="sm"
                className="absolute right-1 top-1/2 -translate-y-1/2 h-7 w-7 p-0"
                onClick={() => setQuery('')}
              >
                <X className="h-4 w-4" />
              </Button>
            )}
          </div>

          <div className="flex-1 overflow-y-auto mt-4 space-y-1 pr-2">
            {filteredCalculators.length === 0 ? (
              <div className="text-center py-8 text-muted-foreground">
                No calculators found for "{query}"
              </div>
            ) : (
              <>
                {filteredCalculators.map((calc, index) => (
                  <Link
                    key={index}
                    to={calc.path}
                    onClick={handleSelect}
                    className="block px-4 py-3 rounded-lg hover:bg-accent transition-colors"
                  >
                    <div className="flex items-center justify-between">
                      <div className="flex items-center space-x-3">
                        <calc.icon className="h-5 w-5 text-primary" />
                        <div>
                          <div className="font-medium flex items-center gap-2">
                            {calc.name}
                            {calc.isAutoGenerated && (
                              <span className="text-xs px-1.5 py-0.5 rounded-full bg-gradient-to-r from-purple-100 to-blue-100 text-purple-700 font-medium">
                                AI
                              </span>
                            )}
                          </div>
                          <div className="text-sm text-muted-foreground">{calc.category}</div>
                        </div>
                      </div>
                    </div>
                  </Link>
                ))}
              </>
            )}
          </div>
        </DialogContent>
      </Dialog>
    );
  }

  if (variant === 'mobile') {
    return (
      <div className="relative w-full">
        <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
        <Input
          placeholder="Search calculators..."
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          className="pl-9 pr-9 h-9 text-sm"
        />
        {query && (
          <Button
            variant="ghost"
            size="sm"
            className="absolute right-0.5 top-1/2 -translate-y-1/2 h-7 w-7 p-0"
            onClick={() => setQuery('')}
          >
            <X className="h-3 w-3" />
          </Button>
        )}
        
        {query && (
          <div className="absolute top-full left-0 right-0 mt-1 bg-background border rounded-lg shadow-lg max-h-[60vh] overflow-y-auto z-50">
            {filteredCalculators.length === 0 ? (
              <div className="text-center py-6 text-sm text-muted-foreground">
                No results for "{query}"
              </div>
            ) : (
              <div className="p-1">
                {filteredCalculators.slice(0, 10).map((calc, index) => (
                  <Link
                    key={index}
                    to={calc.path}
                    onClick={handleSelect}
                    className="block px-3 py-2 rounded-md hover:bg-accent transition-colors"
                  >
                    <div className="flex items-center gap-2">
                      <calc.icon className="h-4 w-4 text-primary flex-shrink-0" />
                      <div className="min-w-0">
                        <div className="font-medium text-sm truncate">{calc.name}</div>
                        <div className="text-xs text-muted-foreground">{calc.category}</div>
                      </div>
                    </div>
                  </Link>
                ))}
                {filteredCalculators.length > 10 && (
                  <div className="px-3 py-2 text-xs text-center text-muted-foreground">
                    +{filteredCalculators.length - 10} more results
                  </div>
                )}
              </div>
            )}
          </div>
        )}
      </div>
    );
  }

  return (
    <div className="w-full space-y-4">
      <div className="relative">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
        <Input
          placeholder="Search calculators by name, category, or keyword..."
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          className="pl-10 pr-10 h-12 text-base"
        />
        {query && (
          <Button
            variant="ghost"
            size="sm"
            className="absolute right-1 top-1/2 -translate-y-1/2 h-8 w-8 p-0"
            onClick={() => setQuery('')}
          >
            <X className="h-4 w-4" />
          </Button>
        )}
      </div>

      {query && (
        <div className="grid gap-3">
          {filteredCalculators.length === 0 ? (
            <div className="text-center py-12 text-muted-foreground">
              No calculators found for "{query}"
            </div>
          ) : (
            <>
              {filteredCalculators.map((calc, index) => (
                <Link
                  key={index}
                  to={calc.path}
                  className="block p-4 rounded-lg border bg-card hover:bg-accent transition-colors"
                >
                  <div className="flex items-center space-x-3">
                    <calc.icon className="h-6 w-6 text-primary" />
                    <div className="flex-1">
                      <div className="font-medium text-lg flex items-center gap-2">
                        {calc.name}
                        {calc.isAutoGenerated && (
                          <span className="text-xs px-2 py-0.5 rounded-full bg-gradient-to-r from-purple-100 to-blue-100 text-purple-700 font-medium">
                            AI
                          </span>
                        )}
                      </div>
                      <div className="text-sm text-muted-foreground">{calc.category}</div>
                    </div>
                  </div>
                </Link>
              ))}
            </>
          )}
        </div>
      )}
    </div>
  );
}
