import { api } from "encore.dev/api";
import { GetCurrenciesResponse } from "./types";

// Gets a list of supported currencies with their details - 170+ world currencies
export const getCurrencies = api<void, GetCurrenciesResponse>(
  { expose: true, method: "GET", path: "/exchange/currencies" },
  async () => {
    // Comprehensive list of 170+ world currencies
    const currencies = [
      // Major Currencies
      { code: "USD", name: "US Dollar", symbol: "$" },
      { code: "EUR", name: "Euro", symbol: "€" },
      { code: "GBP", name: "British Pound Sterling", symbol: "£" },
      { code: "JPY", name: "Japanese Yen", symbol: "¥" },
      { code: "AUD", name: "Australian Dollar", symbol: "A$" },
      { code: "CAD", name: "Canadian Dollar", symbol: "C$" },
      { code: "CHF", name: "Swiss Franc", symbol: "Fr" },
      { code: "CNY", name: "Chinese Yuan", symbol: "¥" },
      { code: "SEK", name: "Swedish Krona", symbol: "kr" },
      { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$" },
      
      // Americas
      { code: "ARS", name: "Argentine Peso", symbol: "$" },
      { code: "BBD", name: "Barbadian Dollar", symbol: "$" },
      { code: "BRL", name: "Brazilian Real", symbol: "R$" },
      { code: "BSD", name: "Bahamian Dollar", symbol: "$" },
      { code: "BZD", name: "Belize Dollar", symbol: "BZ$" },
      { code: "CLP", name: "Chilean Peso", symbol: "$" },
      { code: "COP", name: "Colombian Peso", symbol: "$" },
      { code: "CRC", name: "Costa Rican Colón", symbol: "₡" },
      { code: "CUP", name: "Cuban Peso", symbol: "₱" },
      { code: "DOP", name: "Dominican Peso", symbol: "RD$" },
      { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q" },
      { code: "GYD", name: "Guyanese Dollar", symbol: "$" },
      { code: "HNL", name: "Honduran Lempira", symbol: "L" },
      { code: "HTG", name: "Haitian Gourde", symbol: "G" },
      { code: "JMD", name: "Jamaican Dollar", symbol: "J$" },
      { code: "MXN", name: "Mexican Peso", symbol: "$" },
      { code: "NIO", name: "Nicaraguan Córdoba", symbol: "C$" },
      { code: "PAB", name: "Panamanian Balboa", symbol: "B/." },
      { code: "PEN", name: "Peruvian Sol", symbol: "S/" },
      { code: "PYG", name: "Paraguayan Guaraní", symbol: "Gs" },
      { code: "SRD", name: "Surinamese Dollar", symbol: "$" },
      { code: "TTD", name: "Trinidad and Tobago Dollar", symbol: "TT$" },
      { code: "UYU", name: "Uruguayan Peso", symbol: "$U" },
      { code: "VED", name: "Venezuelan Bolívar", symbol: "Bs.S" },
      
      // Europe
      { code: "ALL", name: "Albanian Lek", symbol: "L" },
      { code: "AMD", name: "Armenian Dram", symbol: "֏" },
      { code: "BAM", name: "Bosnia-Herzegovina Convertible Mark", symbol: "KM" },
      { code: "BGN", name: "Bulgarian Lev", symbol: "лв" },
      { code: "BYN", name: "Belarusian Ruble", symbol: "Br" },
      { code: "CZK", name: "Czech Republic Koruna", symbol: "Kč" },
      { code: "DKK", name: "Danish Krone", symbol: "kr" },
      { code: "GEL", name: "Georgian Lari", symbol: "₾" },
      { code: "HRK", name: "Croatian Kuna", symbol: "kn" },
      { code: "HUF", name: "Hungarian Forint", symbol: "Ft" },
      { code: "ISK", name: "Icelandic Króna", symbol: "kr" },
      { code: "MDL", name: "Moldovan Leu", symbol: "lei" },
      { code: "MKD", name: "Macedonian Denar", symbol: "ден" },
      { code: "NOK", name: "Norwegian Krone", symbol: "kr" },
      { code: "PLN", name: "Polish Zloty", symbol: "zł" },
      { code: "RON", name: "Romanian Leu", symbol: "lei" },
      { code: "RSD", name: "Serbian Dinar", symbol: "Дин." },
      { code: "RUB", name: "Russian Ruble", symbol: "₽" },
      { code: "TRY", name: "Turkish Lira", symbol: "₺" },
      { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴" },
      
      // Asia-Pacific
      { code: "AED", name: "UAE Dirham", symbol: "د.إ" },
      { code: "AFN", name: "Afghan Afghani", symbol: "؋" },
      { code: "BDT", name: "Bangladeshi Taka", symbol: "৳" },
      { code: "BHD", name: "Bahraini Dinar", symbol: ".د.ب" },
      { code: "BND", name: "Brunei Dollar", symbol: "$" },
      { code: "BTN", name: "Bhutanese Ngultrum", symbol: "Nu." },
      { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$" },
      { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp" },
      { code: "ILS", name: "Israeli New Sheqel", symbol: "₪" },
      { code: "INR", name: "Indian Rupee", symbol: "₹" },
      { code: "IQD", name: "Iraqi Dinar", symbol: "ع.د" },
      { code: "IRR", name: "Iranian Rial", symbol: "﷼" },
      { code: "JOD", name: "Jordanian Dinar", symbol: "JD" },
      { code: "KGS", name: "Kyrgystani Som", symbol: "лв" },
      { code: "KHR", name: "Cambodian Riel", symbol: "៛" },
      { code: "KRW", name: "South Korean Won", symbol: "₩" },
      { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك" },
      { code: "KZT", name: "Kazakhstani Tenge", symbol: "лв" },
      { code: "LAK", name: "Laotian Kip", symbol: "₭" },
      { code: "LBP", name: "Lebanese Pound", symbol: "£" },
      { code: "LKR", name: "Sri Lankan Rupee", symbol: "₨" },
      { code: "MMK", name: "Myanmar Kyat", symbol: "K" },
      { code: "MNT", name: "Mongolian Tugrik", symbol: "₮" },
      { code: "MOP", name: "Macanese Pataca", symbol: "MOP$" },
      { code: "MVR", name: "Maldivian Rufiyaa", symbol: ".ރ" },
      { code: "MYR", name: "Malaysian Ringgit", symbol: "RM" },
      { code: "NPR", name: "Nepalese Rupee", symbol: "₨" },
      { code: "OMR", name: "Omani Rial", symbol: "﷼" },
      { code: "PHP", name: "Philippine Peso", symbol: "₱" },
      { code: "PKR", name: "Pakistani Rupee", symbol: "₨" },
      { code: "QAR", name: "Qatari Rial", symbol: "﷼" },
      { code: "SAR", name: "Saudi Riyal", symbol: "﷼" },
      { code: "SGD", name: "Singapore Dollar", symbol: "S$" },
      { code: "SYP", name: "Syrian Pound", symbol: "£" },
      { code: "THB", name: "Thai Baht", symbol: "฿" },
      { code: "TJS", name: "Tajikistani Somoni", symbol: "SM" },
      { code: "TMT", name: "Turkmenistani Manat", symbol: "T" },
      { code: "TWD", name: "Taiwan New Dollar", symbol: "NT$" },
      { code: "UZS", name: "Uzbekistan Som", symbol: "лв" },
      { code: "VND", name: "Vietnamese Dong", symbol: "₫" },
      { code: "YER", name: "Yemeni Rial", symbol: "﷼" },
      
      // Africa
      { code: "AOA", name: "Angolan Kwanza", symbol: "Kz" },
      { code: "BWP", name: "Botswanan Pula", symbol: "P" },
      { code: "BIF", name: "Burundian Franc", symbol: "FBu" },
      { code: "CDF", name: "Congolese Franc", symbol: "FC" },
      { code: "DJF", name: "Djiboutian Franc", symbol: "Fdj" },
      { code: "DZD", name: "Algerian Dinar", symbol: "دج" },
      { code: "EGP", name: "Egyptian Pound", symbol: "£" },
      { code: "ERN", name: "Eritrean Nakfa", symbol: "Nfk" },
      { code: "ETB", name: "Ethiopian Birr", symbol: "Br" },
      { code: "GHS", name: "Ghanaian Cedi", symbol: "¢" },
      { code: "GMD", name: "Gambian Dalasi", symbol: "D" },
      { code: "GNF", name: "Guinean Franc", symbol: "FG" },
      { code: "KES", name: "Kenyan Shilling", symbol: "KSh" },
      { code: "LRD", name: "Liberian Dollar", symbol: "$" },
      { code: "LSL", name: "Lesotho Loti", symbol: "M" },
      { code: "LYD", name: "Libyan Dinar", symbol: "LD" },
      { code: "MAD", name: "Moroccan Dirham", symbol: "MAD" },
      { code: "MGF", name: "Malagasy Franc", symbol: "Fmg" },
      { code: "MUR", name: "Mauritian Rupee", symbol: "₨" },
      { code: "MWK", name: "Malawian Kwacha", symbol: "MK" },
      { code: "MZN", name: "Mozambican Metical", symbol: "MT" },
      { code: "NAD", name: "Namibian Dollar", symbol: "$" },
      { code: "NGN", name: "Nigerian Naira", symbol: "₦" },
      { code: "RWF", name: "Rwandan Franc", symbol: "R₣" },
      { code: "SCR", name: "Seychellois Rupee", symbol: "₨" },
      { code: "SDG", name: "Sudanese Pound", symbol: "ج.س." },
      { code: "SLL", name: "Sierra Leonean Leone", symbol: "Le" },
      { code: "SOS", name: "Somali Shilling", symbol: "S" },
      { code: "STD", name: "São Tomé and Príncipe Dobra", symbol: "Db" },
      { code: "SZL", name: "Swazi Lilangeni", symbol: "E" },
      { code: "TND", name: "Tunisian Dinar", symbol: "د.ت" },
      { code: "TZS", name: "Tanzanian Shilling", symbol: "TSh" },
      { code: "UGX", name: "Ugandan Shilling", symbol: "USh" },
      { code: "XAF", name: "CFA Franc BEAC", symbol: "FCFA" },
      { code: "XOF", name: "CFA Franc BCEAO", symbol: "CFA" },
      { code: "ZAR", name: "South African Rand", symbol: "R" },
      { code: "ZMW", name: "Zambian Kwacha", symbol: "ZK" },
      { code: "ZWL", name: "Zimbabwean Dollar", symbol: "Z$" },
      
      // Oceania
      { code: "FJD", name: "Fijian Dollar", symbol: "$" },
      { code: "PGK", name: "Papua New Guinean Kina", symbol: "K" },
      { code: "SBD", name: "Solomon Islands Dollar", symbol: "$" },
      { code: "TOP", name: "Tongan Paʻanga", symbol: "T$" },
      { code: "VUV", name: "Vanuatu Vatu", symbol: "VT" },
      { code: "WST", name: "Samoan Tala", symbol: "WS$" },
      
      // Other regions and special currencies
      { code: "XDR", name: "Special Drawing Rights", symbol: "SDR" },
      { code: "XAG", name: "Silver Ounce", symbol: "XAG" },
      { code: "XAU", name: "Gold Ounce", symbol: "XAU" },
      { code: "XPD", name: "Palladium Ounce", symbol: "XPD" },
      { code: "XPT", name: "Platinum Ounce", symbol: "XPT" },
      
      // Additional Asian currencies
      { code: "AZN", name: "Azerbaijani Manat", symbol: "₼" },
      { code: "BYR", name: "Belarusian Ruble (old)", symbol: "p." },
      { code: "CLF", name: "Chilean Unit of Account", symbol: "CLF" },
      { code: "CUC", name: "Cuban Convertible Peso", symbol: "CUC$" },
      { code: "IMP", name: "Isle of Man Pound", symbol: "£" },
      { code: "JEP", name: "Jersey Pound", symbol: "£" },
      { code: "KYD", name: "Cayman Islands Dollar", symbol: "$" },
      { code: "LTL", name: "Lithuanian Litas", symbol: "Lt" },
      { code: "LVL", name: "Latvian Lats", symbol: "Ls" },
      { code: "MGA", name: "Malagasy Ariary", symbol: "Ar" },
      { code: "SHP", name: "Saint Helena Pound", symbol: "£" },
      { code: "SVC", name: "Salvadoran Colón", symbol: "$" },
      { code: "XCD", name: "East Caribbean Dollar", symbol: "$" },
      { code: "XPF", name: "CFP Franc", symbol: "₣" }
    ];

    return { currencies };
  }
);