export interface ResumePDFData {
  personalInfo: {
    name: string;
    title: string;
    email: string;
    phone?: string;
    location?: string;
    linkedin?: string;
    website?: string;
  };
  professionalSummary: string;
  experiences: Array<{
    company: string;
    position: string;
    startDate: string;
    endDate?: string;
    current?: boolean;
    description: string;
    achievements?: string[];
  }>;
  education: Array<{
    institution: string;
    degree: string;
    field: string;
    graduationDate?: string;
    gpa?: string;
  }>;
  skills: string[];
  certifications?: string[];
}

export interface InterviewPrepPDFData {
  jobTitle: string;
  company: string;
  questions: Array<{
    question: string;
    answer: string;
    category: string;
  }>;
  tips: string[];
}

export interface CareerDocPDFData {
  title: string;
  content: string;
  metadata?: {
    generatedDate: string;
    author?: string;
    type: string;
  };
}

function createStyledHTML(content: string, title: string, type: string = 'document'): string {
  return `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="UTF-8">
        <title>${title}</title>
        <style>
          @page {
            size: A4;
            margin: 2cm;
          }
          
          body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
          }
          
          h1 {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 10px;
            color: #2563eb;
            border-bottom: 3px solid #2563eb;
            padding-bottom: 10px;
          }
          
          h2 {
            font-size: 18px;
            font-weight: bold;
            margin-top: 24px;
            margin-bottom: 12px;
            color: #1e40af;
          }
          
          h3 {
            font-size: 14px;
            font-weight: bold;
            margin-top: 16px;
            margin-bottom: 8px;
            color: #1e3a8a;
          }
          
          p {
            margin-bottom: 12px;
            text-align: justify;
          }
          
          ul, ol {
            margin: 12px 0;
            padding-left: 24px;
          }
          
          li {
            margin-bottom: 8px;
          }
          
          .header {
            text-align: center;
            margin-bottom: 30px;
          }
          
          .contact-info {
            text-align: center;
            font-size: 12px;
            color: #666;
            margin-bottom: 20px;
          }
          
          .section {
            margin-bottom: 24px;
          }
          
          .question-block {
            background: #f8fafc;
            border-left: 4px solid #2563eb;
            padding: 16px;
            margin-bottom: 20px;
            page-break-inside: avoid;
            break-inside: avoid;
          }
          
          .question {
            font-weight: bold;
            color: #1e40af;
            margin-bottom: 8px;
            font-size: 13px;
          }
          
          .answer {
            color: #475569;
            font-size: 12px;
            line-height: 1.8;
          }
          
          .category-badge {
            display: inline-block;
            background: #dbeafe;
            color: #1e40af;
            padding: 4px 12px;
            border-radius: 12px;
            font-size: 10px;
            font-weight: 600;
            margin-bottom: 8px;
          }
          
          .tip-box {
            background: #fef3c7;
            border-left: 4px solid #f59e0b;
            padding: 12px;
            margin: 16px 0;
            page-break-inside: avoid;
          }
          
          .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #e5e7eb;
            text-align: center;
            font-size: 10px;
            color: #9ca3af;
          }
          
          @media print {
            body {
              padding: 0;
            }
            
            .no-print {
              display: none;
            }
          }
        </style>
      </head>
      <body>
        ${content}
        <div class="footer">
          <p>Generated by Smart Calculator Hubs AI Career Suite • ${new Date().toLocaleDateString()}</p>
          <p>Visit smartcalculatorhubs.com for more AI-powered tools</p>
        </div>
      </body>
    </html>
  `;
}

export function generateResumePDF(resume: ResumePDFData): void {
  const content = `
    <div class="header">
      <h1>${resume.personalInfo.name}</h1>
      <div style="font-size: 16px; color: #475569; margin-bottom: 8px;">${resume.personalInfo.title}</div>
      <div class="contact-info">
        ${resume.personalInfo.email}
        ${resume.personalInfo.phone ? ` | ${resume.personalInfo.phone}` : ''}
        ${resume.personalInfo.location ? ` | ${resume.personalInfo.location}` : ''}
        ${resume.personalInfo.linkedin ? `<br>LinkedIn: ${resume.personalInfo.linkedin}` : ''}
        ${resume.personalInfo.website ? `<br>Website: ${resume.personalInfo.website}` : ''}
      </div>
    </div>
    
    <div class="section">
      <h2>PROFESSIONAL SUMMARY</h2>
      <p>${resume.professionalSummary}</p>
    </div>
    
    <div class="section">
      <h2>WORK EXPERIENCE</h2>
      ${resume.experiences.map(exp => `
        <div style="margin-bottom: 20px;">
          <h3>${exp.position}</h3>
          <div style="color: #64748b; font-size: 12px; margin-bottom: 8px;">
            ${exp.company} | ${exp.startDate} - ${exp.current ? 'Present' : exp.endDate || ''}
          </div>
          <p style="margin-bottom: 8px;">${exp.description}</p>
          ${exp.achievements && exp.achievements.length > 0 ? `
            <ul>
              ${exp.achievements.map(ach => `<li>${ach}</li>`).join('')}
            </ul>
          ` : ''}
        </div>
      `).join('')}
    </div>
    
    <div class="section">
      <h2>EDUCATION</h2>
      ${resume.education.map(edu => `
        <div style="margin-bottom: 16px;">
          <h3>${edu.degree} in ${edu.field}</h3>
          <div style="color: #64748b; font-size: 12px;">
            ${edu.institution}
            ${edu.graduationDate ? ` | Graduated: ${edu.graduationDate}` : ''}
            ${edu.gpa ? ` | GPA: ${edu.gpa}` : ''}
          </div>
        </div>
      `).join('')}
    </div>
    
    ${resume.skills && resume.skills.length > 0 ? `
      <div class="section">
        <h2>SKILLS</h2>
        <p>${resume.skills.join(' • ')}</p>
      </div>
    ` : ''}
    
    ${resume.certifications && resume.certifications.length > 0 ? `
      <div class="section">
        <h2>CERTIFICATIONS</h2>
        <ul>
          ${resume.certifications.map(cert => `<li>${cert}</li>`).join('')}
        </ul>
      </div>
    ` : ''}
  `;
  
  const html = createStyledHTML(content, `${resume.personalInfo.name} - Resume`, 'resume');
  printHTML(html, `${resume.personalInfo.name.replace(/\s+/g, '_')}_Resume.pdf`);
}

export function generateInterviewPrepPDF(data: InterviewPrepPDFData): void {
  console.log('Generating PDF with', data.questions.length, 'questions');
  
  const content = `
    <div class="header">
      <h1>Interview Preparation Guide</h1>
      <div style="font-size: 16px; color: #475569; margin-bottom: 8px;">
        ${data.jobTitle} at ${data.company}
      </div>
      <div style="font-size: 12px; color: #94a3b8; margin-top: 8px;">
        ${data.questions.length} Questions Prepared
      </div>
    </div>
    
    <div class="section">
      <h2>Interview Questions & Answers</h2>
      ${data.questions.map((qa, index) => `
        <div class="question-block">
          <span class="category-badge">${qa.category.replace('-', ' ')}</span>
          <div class="question">Q${index + 1}: ${qa.question}</div>
          <div class="answer">${qa.answer}</div>
        </div>
      `).join('')}
    </div>
    
    ${data.tips && data.tips.length > 0 ? `
      <div class="section" style="page-break-before: always;">
        <h2>Interview Tips & Best Practices</h2>
        ${data.tips.map(tip => `
          <div class="tip-box">
            <strong>💡 Pro Tip:</strong> ${tip}
          </div>
        `).join('')}
      </div>
    ` : ''}
  `;
  
  const html = createStyledHTML(content, `Interview Prep - ${data.jobTitle}`, 'interview');
  console.log('Generated HTML length:', html.length);
  printHTML(html, `Interview_Prep_${data.jobTitle.replace(/\s+/g, '_')}.pdf`);
}

export function generateCoverLetterPDF(coverLetter: string, name: string, company: string): void {
  const content = `
    <div style="margin-bottom: 40px;">
      <p style="white-space: pre-wrap; line-height: 1.8;">${coverLetter}</p>
    </div>
  `;
  
  const html = createStyledHTML(content, `Cover Letter - ${company}`, 'cover-letter');
  printHTML(html, `Cover_Letter_${company.replace(/\s+/g, '_')}.pdf`);
}

export function generateLinkedInOptimizationPDF(data: any): void {
  const content = `
    <div class="header">
      <h1>LinkedIn Profile Optimization</h1>
      <div style="font-size: 14px; color: #64748b;">Generated on ${new Date().toLocaleDateString()}</div>
    </div>
    
    ${data.headline ? `
      <div class="section">
        <h2>Optimized Headline</h2>
        <p style="background: #f1f5f9; padding: 12px; border-radius: 8px; font-weight: 500;">${data.headline}</p>
      </div>
    ` : ''}
    
    ${data.about ? `
      <div class="section">
        <h2>About Section</h2>
        <p style="white-space: pre-wrap;">${data.about}</p>
      </div>
    ` : ''}
    
    ${data.suggestions && data.suggestions.length > 0 ? `
      <div class="section">
        <h2>Optimization Suggestions</h2>
        <ul>
          ${data.suggestions.map((suggestion: string) => `<li>${suggestion}</li>`).join('')}
        </ul>
      </div>
    ` : ''}
  `;
  
  const html = createStyledHTML(content, 'LinkedIn Profile Optimization', 'linkedin');
  printHTML(html, 'LinkedIn_Optimization.pdf');
}

export function generateGenericCareerPDF(data: CareerDocPDFData): void {
  const content = `
    <div class="header">
      <h1>${data.title}</h1>
      ${data.metadata ? `
        <div style="font-size: 12px; color: #64748b;">
          ${data.metadata.generatedDate ? `Generated: ${data.metadata.generatedDate}` : ''}
          ${data.metadata.author ? ` | By: ${data.metadata.author}` : ''}
        </div>
      ` : ''}
    </div>
    
    <div class="section">
      <div style="white-space: pre-wrap; line-height: 1.8;">${data.content}</div>
    </div>
  `;
  
  const html = createStyledHTML(content, data.title, data.metadata?.type || 'document');
  printHTML(html, `${data.title.replace(/\s+/g, '_')}.pdf`);
}

function printHTML(html: string, filename: string): void {
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    
    // Wait for all content to render before printing
    printWindow.onload = () => {
      // Multiple checks to ensure content is fully rendered
      const checkAndPrint = () => {
        const body = printWindow.document.body;
        if (body && body.scrollHeight > 0) {
          printWindow.requestAnimationFrame(() => {
            setTimeout(() => {
              printWindow.focus();
              printWindow.print();
            }, 750);
          });
        } else {
          setTimeout(checkAndPrint, 100);
        }
      };
      checkAndPrint();
    };
  } else {
    console.error('Failed to open print window. Please allow popups for this site.');
    alert('Please allow popups to download PDF. Check your browser settings.');
  }
}

export async function shareCareerDocument(
  content: string, 
  title: string, 
  type: 'resume' | 'cover-letter' | 'interview-prep' | 'linkedin'
): Promise<void> {
  if (navigator.share) {
    try {
      await navigator.share({
        title: title,
        text: content,
      });
    } catch (err) {
      if ((err as Error).name !== 'AbortError') {
        console.error('Share failed:', err);
        fallbackShare(content, title);
      }
    }
  } else {
    fallbackShare(content, title);
  }
}

function fallbackShare(content: string, title: string): void {
  navigator.clipboard.writeText(content);
  alert('Content copied to clipboard! Share it on your preferred platform.');
}
